[tool.poetry]
name = "migrate-rpc-config"
version = "0.1.0"
description = "A CLI tool to migrate Supra RPC config."

[tool.poetry.dependencies]
python = ">=3.10"
tomlkit = ">=0.13.2"
common = { path = "../common" }

[tool.poetry.scripts]
migrate-rpc-config = "migrate_rpc_config.cli:main"